### ISSUE TITLE
找不到DaoSession和CollectDao

### ISSUE THREAD

**Issue by Heyres** [wenhaiz/HiMusic#16]
fork下载后，编译提示如上错误，请问如何解决

**Comment by wenhaiz** [comment]
@Heyres 感谢关注，之前没有 watch 这个仓库，所以一直没收到消息。   
我的 DaoSession 和 XxxDao 都没有上传，MakeProject 后 GreenDao 应该会自动生成，不过最近我准备使用 [ObjectBox](http://objectbox.io/) 替换 GreenDao，欢迎继续关注。
